export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TASK_DATA_LOADED = 'TASK_DATA_LOADED';
export const TASK_DATA_CHANGE = 'TASK_DATA_CHANGE';
export const TASK_DATA_SORT = 'TASK_DATA_SORT';
export const TASK_UPDATED_DATA = 'TASK_UPDATED_DATA';
export const TASK_DATA_RESET = 'TASK_DATA_RESET';

export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const USER_DATA_CHANGE = 'USER_DATA_CHANGE';
export const USER_DATA_SORT = 'USER_DATA_SORT';
export const USER_UPDATED_DATA = 'USER_UPDATED_DATA';
export const USER_DATA_RESET = 'USER_DATA_RESET';

export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_DATA_LOADED = 'PROJECT_DATA_LOADED';
export const PROJECT_DATA_CHANGE = 'PROJECT_DATA_CHANGE';
export const PROJECT_DATA_SORT = 'PROJECT_DATA_SORT';
export const PROJECT_UPDATED_DATA = 'PROJECT_UPDATED_DATA';
export const PROJECT_DATA_RESET = 'PROJECT_DATA_RESET';

export const ADD_PARENT = 'ADD_PARENT';
export const PARENT_DATA_LOADED = 'PARENT_DATA_LOADED';